### ISSUE TITLE
Build issue MX6.0.1

### ISSUE THREAD

**Issue by moes1985** [mendix/ImageCropModule#1]
Version 2.1 of the Cropper.mpk does not work correctly with MX6.0.1. It compiles, but gives a build error when creating a deployment package or when using the Check Widgets functionality.

**Comment by JelteMX** [comment]
Confirmed. It looks like we left some old files in the widget when updating to MX6. Will see if I can update this widget this week.

**Comment by JelteMX** [comment]
Fixed in [v2.1.1](https://github.com/mendix/ImageCropModule/releases/tag/v2.1.1), should be updated in the AppStore tomorrow
