### ISSUE TITLE
Mendix 8

### ISSUE THREAD

**Issue by Mochocolate** [mendix/ImageCropModule#11]
When exporting the module from a mendix 7 modeler and importing it in Mendix 8, the map 'implimentations' will not be imported which leads to compile errors. Simple fix: copy and paste implimentation map from other mendix 7 app to javasource > imagecrop after importing imagecrop module in a mendix 8 app.

**Comment by mmehmetAliIzci** [comment]
We fixed this issue with Mx 8 release which you can find in the mendix appstore.
